services:
    historischer-spieleabend:
        image: faulo/farah:8.3
        volumes:
            - .:/var/www2
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        ports:
            - 80:80
            - 443:443
                