services:
    farah:
        image: tmp/historischer-spieleabend:latest
        volumes:
            - data:C:/www/data
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        ports:
            - 80:80
            - 443:443
volumes:
    data:
                